### ISSUE TITLE
Cyphal / DroneCAN in introduction 

### ISSUE THREAD

**Issue by sainquake** [InnopolisAero/inno_uavcan_node_binaries#12]
Here https://raccoonlabdev.github.io/docs/guide/#introduction 
its better to write

>  Cyphal / DroneCAN  (old name UAVCAN)

 instead of 

> [DroneCAN (opens new window)](https://dronecan.github.io/)/[Cyphal (opens new window)](https://opencyphal.org/)(old name UAVCAN)

**Comment by PonomarevDA** [comment]
fixed
