### ISSUE TITLE
Mini Node v2 Not Fully Supported by Cyphal v1.4 Release

### ISSUE THREAD

**Issue by ActuonixElec** [InnopolisAero/inno_uavcan_node_binaries#15]
Release package v1.4 for Cyphal has a compiled binary for the Micro, but not the Mini v2.  When flashing the Mini with this firmware, it works, but I can only control PWM1, not PWM2-4.  I fixed this by reverting back to the v1.2 release of Cyphal (separate binary for Mini v2), which gave me control over all PWM channels.  
I think the only issue is that the [firmware update guide](https://docs.raccoonlab.co/guide/intro/firmware_upload.html#step-1-download-firmware) links to v1.4 for both the Mini & Micro.  I think that either the v1.4 FW should be recompiled to include a Mini binary too, or update that webpage to link to the v1.2 release for the Mini specifically.

**Comment by PonomarevDA** [comment]
Thanks for opening the issue.
The new firmwares for Mini v2 and Micro nodes have been released: [v1.5.10](https://github.com/RaccoonlabDev/docs/releases/tag/v1.5.10).
I've updated the relevant sections in the docs with the new link:
- [Micro and Mini v2 release history](https://docs.raccoonlab.co/guide/can_pwm/can_pwm_cyphal.html#_4-6-versions)
- [Latest firmwares](https://docs.raccoonlab.co/guide/intro/firmware_upload.html#step-1-download-firmware)

**Comment by ActuonixElec** [comment]
Thank you very much for the prompt action!
